spring:
  application.name: orders-service
  profiles.default: local

server:
  port: 8080

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.probes.enabled: true

# ----- Local profile -----
---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
aws:
  region: us-east-1
  sqs:
    queue-name: orders-created-queue
  s3:
    bucket: acme-orders-attachments-local